<#
PowerShell Profile Configuration
Sets up comprehensive PowerShell profile with Oh-My-Posh, PSReadLine, aliases, and helper functions.
#>
$ErrorActionPreference = 'Stop'

Write-Host "[PROFILE] Configuring PowerShell profile..."

# Ensure profile exists
if (-not (Test-Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    Write-Host "  Created profile: $PROFILE" -ForegroundColor Yellow
}

# Read existing profile
$existingContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue

# Build comprehensive profile
$profileContent = @'
# ============================================================================
# PowerShell Profile - Auto-generated by devMachine setup
# ============================================================================

# Oh My Posh - Enhanced prompt
if (Get-Command oh-my-posh -ErrorAction SilentlyContinue) {
    $poshTheme = "$env:POSH_THEMES_PATH\paradox.omp.json"
    if (Test-Path $poshTheme) {
        oh-my-posh init pwsh --config $poshTheme | Invoke-Expression
    } else {
        # Fallback to default theme
        oh-my-posh init pwsh | Invoke-Expression
    }
}

# PSReadLine - Enhanced command-line editing
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine

    # Prediction settings
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -PredictionViewStyle ListView
    Set-PSReadLineOption -EditMode Windows
    Set-PSReadLineOption -BellStyle None

    # History settings
    Set-PSReadLineOption -HistorySearchCursorMovesToEnd
    Set-PSReadLineOption -MaximumHistoryCount 10000

    # Key bindings
    Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
    Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    Set-PSReadLineKeyHandler -Key Ctrl+d -Function DeleteChar
    Set-PSReadLineKeyHandler -Key Ctrl+w -Function BackwardDeleteWord

    # Colors
    Set-PSReadLineOption -Colors @{
        Command = 'Yellow'
        Parameter = 'Green'
        Operator = 'Magenta'
        Variable = 'Blue'
        String = 'Cyan'
        Number = 'White'
        Type = 'DarkYellow'
        Comment = 'DarkGray'
    }
}

# posh-git - Git prompt integration
if (Get-Module -ListAvailable -Name posh-git) {
    Import-Module posh-git
}

# mise - Universal toolchain manager
if (Get-Command mise -ErrorAction SilentlyContinue) {
    try {
        # Use a timeout job to prevent hanging
        $miseJob = Start-Job -ScriptBlock { mise activate pwsh }
        if (Wait-Job $miseJob -Timeout 5) {
            $miseInit = Receive-Job $miseJob | Out-String
            if ($miseInit -and $miseInit.Trim()) {
                Invoke-Expression $miseInit
            }
        } else {
            # mise is hanging, skip it
            Write-Warning "mise activation timed out - skipping"
        }
        Remove-Job $miseJob -Force -ErrorAction SilentlyContinue
    } catch {
        Write-Warning "mise activation failed: $_"
    }
}

# ============================================================================
# Aliases
# ============================================================================

# Git shortcuts (avoiding conflicts with built-in aliases)
Set-Alias -Name g -Value git
Set-Alias -Name gs -Value 'git status'
# Note: gp, gc, gps, gcm are built-in PowerShell aliases
# Using git-specific prefixes to avoid conflicts
Set-Alias -Name gpl -Value 'git pull'
Set-Alias -Name gpu -Value 'git push'  # gps conflicts with Get-Process
Set-Alias -Name gco -Value 'git commit'  # gcm conflicts with Get-Command
Set-Alias -Name ga -Value 'git add'
Set-Alias -Name gd -Value 'git diff'

# Docker shortcuts
Set-Alias -Name d -Value docker
Set-Alias -Name dc -Value docker-compose
Set-Alias -Name k -Value kubectl

# Cloud CLIs
Set-Alias -Name tf -Value terraform
Set-Alias -Name az -Value 'az.cmd'  # Azure CLI

# Editor
Set-Alias -Name vi -Value code
Set-Alias -Name vim -Value code
Set-Alias -Name nano -Value code

# System shortcuts
Set-Alias -Name which -Value Get-Command
Set-Alias -Name grep -Value Select-String
Set-Alias -Name ll -Value Get-ChildItem

# ============================================================================
# Helper Functions
# ============================================================================

function which($name) {
    Get-Command $name -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
}

function touch($file) {
    "" | Out-File $file -Encoding ASCII
}

function mkcd($dir) {
    New-Item -ItemType Directory -Path $dir -Force | Set-Location
}

function .. { Set-Location .. }
function ... { Set-Location ..\.. }
function .... { Set-Location ..\..\.. }

function Get-PublicIP {
    (Invoke-WebRequest -Uri "https://api.ipify.org" -UseBasicParsing).Content
}

function Get-LocalIP {
    Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object { $_.InterfaceAlias -notlike "*Loopback*" } |
        Select-Object IPAddress, InterfaceAlias
}

function Update-Profile {
    . $PROFILE
    Write-Host "Profile reloaded!" -ForegroundColor Green
}

function Edit-Profile {
    code $PROFILE
}

function Find-File($pattern) {
    Get-ChildItem -Recurse -Filter $pattern -ErrorAction SilentlyContinue
}

function Find-InFile($pattern, $path = ".") {
    Get-ChildItem -Path $path -Recurse -File |
        Select-String -Pattern $pattern |
        Group-Object Path |
        Select-Object Name
}

function Get-DiskSpace {
    Get-Volume |
        Where-Object { $_.DriveLetter } |
        Select-Object DriveLetter,
            @{Name="Size(GB)";Expression={[math]::Round($_.Size/1GB,2)}},
            @{Name="Free(GB)";Expression={[math]::Round($_.SizeRemaining/1GB,2)}},
            @{Name="Free(%)";Expression={[math]::Round(($_.SizeRemaining/$_.Size)*100,2)}}
}

function Get-SystemInfo {
    $os = Get-CimInstance Win32_OperatingSystem
    $cpu = Get-CimInstance Win32_Processor
    $mem = Get-CimInstance Win32_PhysicalMemory

    [PSCustomObject]@{
        OS = $os.Caption
        Version = $os.Version
        Architecture = $os.OSArchitecture
        CPU = $cpu.Name
        Cores = $cpu.NumberOfCores
        "RAM(GB)" = [math]::Round(($mem | Measure-Object Capacity -Sum).Sum / 1GB, 2)
        Uptime = (Get-Date) - $os.LastBootUpTime
    }
}

function Clean-Path {
    $env:Path = ($env:Path -split ';' | Select-Object -Unique) -join ';'
    Write-Host "PATH cleaned and deduplicated" -ForegroundColor Green
}

# Docker helpers
function docker-clean {
    docker system prune -a --volumes -f
    Write-Host "Docker cleanup complete" -ForegroundColor Green
}

function docker-stopall {
    docker stop $(docker ps -aq)
}

function docker-rmall {
    docker rm $(docker ps -aq)
}

# Git helpers
function git-main {
    $mainBranch = git remote show origin | Select-String "HEAD branch" | ForEach-Object { $_.ToString().Split()[-1] }
    git checkout $mainBranch
}

function git-clean-branches {
    git fetch --prune
    git branch -vv | Select-String ': gone]' | ForEach-Object {
        $branch = $_.ToString().Trim().Split()[0]
        git branch -D $branch
    }
}

function git-undo {
    git reset --soft HEAD~1
}

# ============================================================================
# Startup Info
# ============================================================================

# Show PowerShell version
# Write-Host "PowerShell $($PSVersionTable.PSVersion)" -ForegroundColor Cyan

# Show tip of the day (optional - comment out if annoying)
# $tips = @(
#     "Tip: Use 'Get-SystemInfo' to see system details",
#     "Tip: Use 'Get-DiskSpace' to check disk usage",
#     "Tip: Use 'git-clean-branches' to remove stale branches",
#     "Tip: Use 'docker-clean' to free up Docker space",
#     "Tip: Use 'Update-Profile' to reload this profile"
# )
# Write-Host ($tips | Get-Random) -ForegroundColor DarkGray
'@

# Check if profile already has custom content
if ($existingContent -match "devMachine setup") {
    Write-Host "  Profile already configured, updating..." -ForegroundColor Yellow
    # Backup existing profile
    Copy-Item $PROFILE "$PROFILE.backup.$(Get-Date -Format 'yyyyMMdd-HHmmss')"
}

# Write new profile
$profileContent | Out-File -FilePath $PROFILE -Encoding UTF8 -Force

Write-Host "  ✅ PowerShell profile configured" -ForegroundColor Green

# Install PSReadLine if not present
if (-not (Get-Module -ListAvailable -Name PSReadLine)) {
    Write-Host "`n[PSREADLINE] Installing PSReadLine module..."
    try {
        Install-Module -Name PSReadLine -Scope CurrentUser -Force -AllowClobber
        Write-Host "  ✅ PSReadLine installed" -ForegroundColor Green
    } catch {
        Write-Warning "PSReadLine installation failed: $_"
    }
}

# Configure console font for Nerd Font icons (PowerShell console)
Write-Host "`n[CONSOLE] Configuring console font for Nerd Font support..."
try {
    # Registry paths for PowerShell console configurations
    $consolePaths = @(
        "HKCU:\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe",
        "HKCU:\Console\C:_Program Files_PowerShell_7_pwsh.exe"
    )

    # Create registry paths if they don't exist
    foreach ($path in $consolePaths) {
        if (-not (Test-Path $path)) {
            New-Item -Path $path -Force | Out-Null
        }
    }

    # Font settings for JetBrains Mono Nerd Font with auto-detection
    $installedJetBrainsFonts = Get-ChildItem "$env:windir\Fonts" -Filter "*JetBrains*" -ErrorAction SilentlyContinue | Where-Object {
        $_.Name -match "NF.*Regular\.ttf$|Nerd.*Font.*Regular\.ttf$"
    }

    $fontName = if ($installedJetBrainsFonts) {
        $installedJetBrainsFonts[0].BaseName
    } else {
        "JetBrainsMono NF"  # Fallback
    }

    Write-Host "    Using font: $fontName" -ForegroundColor Gray

    $fontSettings = @{
        "FaceName" = $fontName
        "FontFamily" = 54  # Modern font family
        "FontSize" = 0x000C0000  # Size 12 (high word = height, low word = width)
        "FontWeight" = 400  # Normal weight
    }

    # Additional console improvements
    $consoleSettings = @{
        "QuickEdit" = 1        # Enable quick edit mode
        "InsertMode" = 1       # Insert mode enabled
        "HistoryBufferSize" = 50    # Command history size
        "NumberOfHistoryBuffers" = 4  # Number of history buffers
    }

    # Apply font and console settings
    foreach ($path in $consolePaths) {
        foreach ($setting in ($fontSettings + $consoleSettings).GetEnumerator()) {
            Set-ItemProperty -Path $path -Name $setting.Key -Value $setting.Value -Type DWord -ErrorAction SilentlyContinue
        }
    }

    Write-Host "  ✅ Console font configured for Nerd Font icons" -ForegroundColor Green
    Write-Host "    Restart PowerShell console to see proper Git icons" -ForegroundColor Gray
} catch {
    Write-Warning "Console font configuration failed: $_"
}

# Configure VS Code terminal font for Nerd Font icons
Write-Host "`n[VSCODE] Configuring VS Code terminal font..."
try {
    $vscodeSettingsPath = "$env:APPDATA\Code\User\settings.json"

    if (Test-Path $vscodeSettingsPath) {
        $vscodeSettings = Get-Content $vscodeSettingsPath -Raw | ConvertFrom-Json

        # Add or update terminal font settings
        if (-not $vscodeSettings.'terminal.integrated.fontFamily') {
            $vscodeSettings | Add-Member -MemberType NoteProperty -Name 'terminal.integrated.fontFamily' -Value 'JetBrainsMono Nerd Font' -Force
        } else {
            $vscodeSettings.'terminal.integrated.fontFamily' = 'JetBrainsMono Nerd Font'
        }

        if (-not $vscodeSettings.'terminal.integrated.fontSize') {
            $vscodeSettings | Add-Member -MemberType NoteProperty -Name 'terminal.integrated.fontSize' -Value 12 -Force
        }

        $vscodeSettings | ConvertTo-Json -Depth 10 | Set-Content $vscodeSettingsPath -Encoding UTF8
        Write-Host "  ✅ VS Code terminal font configured" -ForegroundColor Green
        Write-Host "    Reload VS Code terminal to see proper Git icons" -ForegroundColor Gray
    } else {
        Write-Host "  ℹ️  VS Code settings not found (run VS Code once to create)" -ForegroundColor Gray
    }
} catch {
    Write-Warning "VS Code font configuration failed: $_"
}

Write-Host "`n[OK] Profile configuration complete!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "Profile location: $PROFILE" -ForegroundColor Yellow
Write-Host "Reload profile: Update-Profile" -ForegroundColor Yellow
Write-Host "Edit profile: Edit-Profile" -ForegroundColor Yellow
Write-Host "Console font: JetBrainsMono NF (for Git icons)" -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "`n💡 Restart PowerShell console to see proper Git icons!" -ForegroundColor Yellow
